### ISSUE TITLE
Makefile broken under macOS

### ISSUE THREAD

**Issue by winkj** [Sensirion/embedded-sgp#11]
Some of the Makefile command seem to use GNU specific switches, which break it under macOS:

1) macOS cp doesn't have '-l'
2) macOS "sed -i" doesn't work; some details here" https://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed

**Comment by abrauchli** [comment]
Thanks, we'll look into it shortly..

**Comment by abrauchli** [comment]
fixed in #15
