### ISSUE TITLE
Problem with SHT40 on dev board SVM40 using either Arduino or Particle

### ISSUE THREAD

**Issue by roviraa** [Sensirion/embedded-sgp#120]
Hi, I recently received the SVM40 dev board and I am  facing a problem from the sensor init function. I have tried either on Arduino nano (with the arduino IDE) or Particle Argon (with vs code) and the result is the same : error -11.
As far as what I found, this error seems to be related to the SHT40. But I can't say if it is due to communication, wiring, etc...
I followed the wiring configurations: 
Red cable = VDD
Black cable = GND
Green cable = SDA
Yellow cable = SCL
Does anyone got the same issue ?

**Comment by rnestler** [comment]
Hi @roviraa 
As mentioned in the README: The SVM-40 is a complete module with a separate microcontroller. Check out https://github.com/Sensirion/embedded-svm40.

**Comment by rnestler** [comment]
I also edited the release notes for https://github.com/Sensirion/embedded-sgp/releases/tag/7.1.0 to mention the svm40 driver.

**Comment by roviraa** [comment]
Hi @rnestler,
Oopsy ! Looks like another RTFM syndrom... 
I just tested with the mentioned repos and it works fine.
Sorry about that and thanks for replying me.

**Comment by rnestler** [comment]
No problem, good to hear that you got it working slightly_smiling_face:
