### ISSUE TITLE
Does SGP40 have a python handler?

### ISSUE THREAD

**Issue by hnwangkg-ezio** [Sensirion/embedded-sgp#121]
Does SGP40 have a python handler?

**Comment by rnestler** [comment]
Sorry @hnwangkg-ezio I don't really get what you are asking for. What are you trying to achieve? Do you ask if there is a Python library to use the SGP40 sensor?
We provide Python libraries for the [SVM40 evaluation kit](https://www.sensirion.com/en/environmental-sensors/evaluation-kit-sek-svm40/) (which contains an SGP40 sensor) for UART and I2C:
 * https://pypi.org/project/sensirion-i2c-svm40/
 * https://pypi.org/project/sensirion-shdlc-svm40/

**Comment by rnestler** [comment]
I'll close this due to inactivity. Feel free to reopen if you have any further issue.
