### ISSUE TITLE
VOC algorithm SGP40 on 8-bit MCU issues

### ISSUE THREAD

**Issue by jirihusak** [Sensirion/embedded-sgp#124]
Hi,
I'm testing a library for SGP40 and I spent lot of time debuging, why the voc algorithm working on PC but not working on 8-bit MCU (Michrochip PIC18).

The issue is in file
function : static fix16_t fix16_mul(fix16_t inArg0, fix16_t inArg1)
when is at least one parameter negative, than the multiply overflow and returns unexpected result.
I make quick fix and in the algorithm I'm working only with positive numbers
->1. chceck if the result should be positive or negative 
->2. both of arguments make positive (abs() )
->3. if result should be negative, return -ret_val;

**Comment by abrauchli** [comment]
Hi @jirihusak many thanks for taking the time to debug and report this! We'll investigate the issue and possibly import your fix. Note that due to the holidays it will likely drag into next year. We'll leave this issue open until then.

Kind regards and merry Christmas :santa: 
Andreas

**Comment by MBjoern** [comment]
Hi, We're working on a fix for this issue and will publish an updated version for 8bit MCUs soon.

Thank you for your patience

**Comment by MBjoern** [comment]
Hi jirihusak

We have updated the VOC algorithm to fix the 8-bit mcu fix point aritmetic issue.
Would you mind testing the updated version (currently in master, there's no release just yet) and update us, if the mentioned issue can be resolved?

Best regards
Björn
