### ISSUE TITLE
Request: Python port of the SGP40 VOC Index code

### ISSUE THREAD

**Issue by siddacious** [Sensirion/embedded-sgp#125]
Hello, thanks for making this code available! If possible, a python port of the SGP40 VOC index code would be super helpful.

**Comment by abrauchli** [comment]
Hi @siddacious thanks for your interest and your request. We'll look into this and get back to you sometime in January.

**Comment by siddacious** [comment]
@abrauchli Thanks! We (Adafruit) have a breakout for the SGP40 that we're promoting and would love to include full CircuitPython support!

**Comment by rnestler** [comment]
@siddacious  Would it work for you if we simply wrap our C VOC algorithm in a Python package and publish it on pypi.org? Because that would be a lot easier for us to implement, since we already use it that way internally anyways :slightly_smiling_face:

**Comment by rnestler** [comment]
@siddacious Ping.

**Comment by 1960pghpirates** [comment]
@rnestler Is the plan to release a Python port of the SGP40 VOC index code?  Or at minimum, a Python package as you mentioned above?   Those of us who prefer Raspberry Pi to Arduino and want to use this sensor to its fullest capabilities will need it.  Thanks.

**Comment by rnestler** [comment]
@1960pghpirates  The plan is indeed wrap the C VOC Algorithm in a Python package and provide it on pypi.org. But it currently hasn't high priority for us, due to being busy with the newer sensors like the [SCD4x sensor family](https://github.com/sensirion/?q=scd4x).

You can use the embedded-sgp code on a raspberry pi, but if I understand you correctly the issue is more that you don't want to use C but Python, right?

**Comment by 1960pghpirates** [comment]
Yes, I would prefer to use Python instead of C.  Adafruit has some kind of support for Python, but I think it can only extract the raw gas value.   To get the VOC Index value would require the change you are talking about.   [https://learn.adafruit.com/adafruit-sgp40/python-circuitpython](url)

**Comment by ImanolGo** [comment]
@rnestler Has your team been able to pack the VOC algorithm into a Python package?
It would be great to have support for Python.

**Comment by mjaakkol** [comment]
I made Rust port of the driver and the algorithm using floating points. You don't need to know Rust to port that into Python. Lot of the basic code will work "as-is". However, you want to take my floating point version as your starting point https://github.com/mjaakkol/sgp40-rs/blob/1f6f6eb357ab4a3480e2f50e6ab5b165684097e0/src/vocalg.rs as my newer Fixed point one is a bit messier and incomplete. Doing the conversion shouldn't take more than few hours of your time.

**Comment by ImanolGo** [comment]
@mjaakkol thanks for the tip. The code really looks straightforward. I'll definitely  have a look at it.

**Comment by itsnils** [comment]
For all those who were looking for the Python algorithm. : [Link](https://github.com/DFRobot/DFRobot_SGP40)

**Comment by ImanolGo** [comment]
@itsnils Great, thanks for sharing this library. I just tested it on my Raspberry Pi 4 B and I can now perfectly read the VOC index.
