### ISSUE TITLE
Request to copy some code

### ISSUE THREAD

**Issue by SenexCrenshaw** [Sensirion/embedded-sgp#128]
I am developing a SGP40 driver for esphome. 
https://esphome.io/

I would like to use your algorithm in your library but including the files might interfere with esphome's license as well as our automated linting/building doesn't like your formats/naming convention.

Is there an issue with me  copying the function/pieces of code that I need out of your library into my own source? There are a few of us who would love to incorporate this into esphome. Im just being sensitive to licenses.

**Comment by rnestler** [comment]
> might interfere with esphome's license

Under what terms is the result licensed? The code in this repository is licensed under the terms of: https://github.com/Sensirion/embedded-sgp/blob/master/LICENSE

**Comment by rnestler** [comment]
Also: Did you see the [SVM40](https://www.sensirion.com/en/environmental-sensors/evaluation-kit-sek-environmental-sensing/evaluation-kit-sek-svm40/) module already? It includes an SGP40 and SHTC3 sensor and the mentioned algorithm and is thus much easier to use. We also provide embedded and Arduino drivers for it: https://github.com/sensirion/?q=svm40

**Comment by SenexCrenshaw** [comment]
I actually read that after this post and I will include a reference back to
this license in this repo. I think im good. I pushed a new PR and I know
some folks are looking forward to trying this out.

In case your are interested: https://github.com/esphome/esphome/pull/1513

**Comment by rnestler** [comment]
I guess we can close this issue then. Thanks for adding support for our sensors to esphome :slightly_smiling_face:

**Comment by SenexCrenshaw** [comment]
Ah. sorry i just realized how much SVM40 code is. I will incorporate that.
I would make a PR for the SVM40 but dont have access to any..
Hint hint ;)

**Comment by rnestler** [comment]
@SenexCrenshaw  If you email me your postal address I can send you an SVM40 evaluation kit :slightly_smiling_face:

**Comment by SenexCrenshaw** [comment]
@rnestler Sounds great. I tried my best but couldnt find your address.

**Comment by SenexCrenshaw** [comment]
I did btw look at the new code. it is much cleaner but the mcu on that dev board handles the VOC index algorithm, right?

**Comment by rnestler** [comment]
> it is much cleaner but the mcu on that dev board handles the VOC index algorithm, right?

Thanks. Correct, the MCU on the board handles the periodic measurements and the VOC index algorithm.

**Comment by SenexCrenshaw** [comment]
Cool, thank you for everything and sorry for commenting on a closed thread.
