### ISSUE TITLE
VOC algorithm SGP40 on 8-bit MCU (Microchip PIC18) failed

### ISSUE THREAD

**Issue by hank2022** [Sensirion/embedded-sgp#131]
I use MPLAB X DE and XC8 as platform in my project.
 The project is a 8-bit MCU application(Microchip PIC18) which employs SGP40+SHT35 to get VOC Index.

Since I have got raw VOC data through my firmware,  I just call “VocAlgorithm_init()” and “VocAlgorithm_process()” to calculate VOC-Index. 

After power on , VOC-Index=0 is as expected  in 45 seconds. But after then, VOC-Index = 500 no change.
 
Below are portions of my codes:
 
Unsigned int voc_raw_data
int32_t voc_index
int32_t voc_raw_data
int32_t local_voc_index

VocAlgorithmParams voc_algorithm_params;

// Initialize VOC Engine
VocAlgorithm_init(&voc_algorithm_params);

lp:

//get SRAW
get_voc_raw_data(); // voc_raw_data =29011, for example

//for calculation of VOC index/TVOC                    
  VocAlgorithm_process(&voc_algorithm_params, voc_raw_data, &local_voc_index);

 waiting_for_1s();
 
voc_index= local_voc_index

goto lp;

I am aware that Jieihusak raised an issue #124 on GitHub ---”VOC algorithm SGP40 on 8-bit MCU issues #124”  on Dec 14,2020,

I debugged and found the same issue in my application. Followed  Jieihusak's instruction, I tried but failed. 

Please fix the issue if apply.
Thanks

**Comment by MBjoern** [comment]
We'll publish a corrected version a.s.a.p. Thank you for your patience.

**Comment by MBjoern** [comment]
Hi Hank

We have updated the VOC algorithm to fix the 8-bit mcu fix point aritmetic issue.
Would you mind testing the updated version (currently in master, there's no release just yet) and update us, if the mentioned issue can be resolved?

Best regards
Björn

**Comment by hank2022** [comment]
Hi Björn,

Thank you for you  work.

I desire to test and use it for our suspended project.

I am going to download and test it.

Thanks

Hank

**Comment by hank2022** [comment]
Hi Björn,

The new version  https://github.com/Sensirion/embedded-sgp/releases/tag/7.1.2)  seems work fine for me.

But  it seems  a bug in “sensirion_voc_algorithm.C”  when I debugged it.
The bug makes my program dead lock.

For my using, it seems OK so far after I changed the sub-function “fix16_cast_to_int()” as below:


static inline int32_t fix16_cast_to_int(fix16_t a) {
    //return (a >= 0) ? (a >> 16) : -((-a) >> 16); //masked by Hank
    return (a >> 16); //added by Hank
}


Could you double check the sub-function “fix16_cast_to_int()”?

Thanks

Hank

**Comment by MBjoern** [comment]
Hi Hank

Thank you for your feedback... we'll look into it.

Best regards

**Comment by MBjoern** [comment]
Hi Hank

Thank you for your feedback... we'll look into it.

Best regards

**Comment by hank2022** [comment]
Yes, the bug is fixed.
Thanks Sensirion-Bot.
Hank

**Comment by MBjoern** [comment]
That's great to hear. I hope you had a good experience working with Sensirion sensors.
In that case I will close this issue ...
