### ISSUE TITLE
Initial blackout period

### ISSUE THREAD

**Issue by remyhx** [Sensirion/embedded-sgp#134]
Hi, I couldn't find about the first blackout periode recommendations. Is it possible to start with a for loop to initialize the voc index algoritm, so it can start up quicker? 

At this moment i measure until index = 90 or max 200 measurement points with 50 ms delay, to switch after that initial period to a 2 minute measurement loop.

**Comment by MBjoern** [comment]
The algorithm and sensor expects you to measure with a constant frequency of 1 Hz, otherwise it won't give you reasonable results. The wait time isn't that long, so that should be fine. The algorithm can also not be started quicker using for loops, as this defeats the purpose of the initial phase.

**Comment by remyhx** [comment]
Thx for your answer. No problem, better save then sorry!

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Björn Muntwyler ***@***.***>
Verzonden: Tuesday, May 25, 2021 10:08:16 AM
Aan: Sensirion/embedded-sgp ***@***.***>
CC: Remy Hurx ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Sensirion/embedded-sgp] Initial blackout period (#134)


The algorithm and sensor expects you to measure with a constant frequency of 1 Hz, otherwise it won't give you reasonable results. The wait time isn't that long, so that should be fine. The algorithm can also not be started quicker using for loops, as this defeats the purpose of the initial phase.
