### ISSUE TITLE
Errors can be tossed when compiling with LLVM

### ISSUE THREAD

**Issue by bradaspencerorg** [Sensirion/embedded-sgp#137]
Small issue...  when compiling the VOC algorithm code with LLVM and -Werror -Wparentheses-equality errors will be tossed for lines that look like this:

if ((params->m_Mean_Variance_Estimator___Initialized == false)) {

to quiet LLVM these need to be (at the very least the extra parens need to be removed)

if (!params->m_Mean_Variance_Estimator___Initialized) {

There are two such lines in sensirion_voc_algorithm.c one around line 599 and another around 776.  Since my interest was only in the VOC algorithm itself, an exhaustive search though the code for other instances of this was not done.  This change should, in no way, effect how the code operates.

**Comment by rnestler** [comment]
Hi @bradaspencerorg 

Thanks for your feedback. Feel free to open a pull request with the proposed changes :slightly_smiling_face:

**Comment by bradaspencerorg** [comment]
Pull request https://github.com/Sensirion/embedded-sgp/pull/138 was created.

**Comment by bradaspencerorg** [comment]
PR was merged..  Thanks...
