### ISSUE TITLE
SGP40 VOC algorithm

### ISSUE THREAD

**Issue by qati** [Sensirion/embedded-sgp#140]
Hello,

I know in the datasheet say sampling rate for VOC algorithm should be 1Hz. In the code I don't see any constraint to increase this to few seconds, and turn off the heater in the meantime. Or that would render the VOC index unusable?

PS: I am trying to build battery enabled device, and just looking for ways to increase battery life.

**Comment by rnestler** [comment]
Hi @qati 

Indeed the algorithm is tuned for a sampling rate of 1Hz and will behave differently when used with a different sampling rate. See also https://github.com/Sensirion/embedded-sgp/issues/136

**Comment by MBjoern** [comment]
Hi @qati 

Please have a look here, for the latest version of the Gas Index Algorithm.

https://github.com/Sensirion/gas-index-algorithm

If you decide to change the sampling interval, make sure to also adjust the definition of the sampling interval in the h.file of the algorithm. The setup is tuned for 1Hz. If you decide to use a different sampling interval and turn off the heater in the mean time, then the MOX will react differently and the behavior of the sensor may differ. The algorithm allows to use different sampling interval, but the sensor may react differently to it's environment.

For Sensor Specific details beyond the source code, please contact info@sensirion.com
