### ISSUE TITLE
SVM30 on Arduino

### ISSUE THREAD

**Issue by olirehacek** [Sensirion/embedded-sgp#56]
Hi,

I know this is a Issues category, but can you please point me into a right direction to implement the SVM30 on Arduino ? 

Thank You.

**Comment by rnestler** [comment]
Hi @olirehacek 

You can take a look at the [Arduino sample implementation](https://github.com/Sensirion/embedded-common/tree/d7389dff12a7eafad952246b6577c65f6d30786b/hw_i2c/sample-implementations/arduino) in the embedded-common repository.

**Comment by olirehacek** [comment]
> Hi @olirehacek
> 
> You can take a look at the [Arduino sample implementation](https://github.com/Sensirion/embedded-common/tree/d7389dff12a7eafad952246b6577c65f6d30786b/hw_i2c/sample-implementations/arduino) in the embedded-common repository.

Got that! Working flawlessly on Ardu Uno and even ESP8266/ESP32s.

Thanks 👍

**Comment by rnestler** [comment]
I'll close this, since you got it working. Feel free to open new issues if you encounter any troubles :slightly_smiling_face:

**Comment by worldburger** [comment]
> > Hi @olirehacek
> > You can take a look at the [Arduino sample implementation](https://github.com/Sensirion/embedded-common/tree/d7389dff12a7eafad952246b6577c65f6d30786b/hw_i2c/sample-implementations/arduino) in the embedded-common repository.
> 
> Got that! Working flawlessly on Ardu Uno and even ESP8266/ESP32s with few mods.
> 
> Thanks 👍

@olirehacek glad you got it working, could you post your code? It'd be super helpful. I feel rather lost on this one...
