### ISSUE TITLE
Request: Arduino example for SVM30

### ISSUE THREAD

**Issue by sgowdarcsu** [Sensirion/embedded-sgp#62]
I'm fairly new at coding but I did try and implement your example usage code into my Arduino code but it didn't seem to work for me. I included all the required Libraries and made changes as list in the instructions but there is no reading on the serial monitor.

**Comment by worldburger** [comment]
@sgowdarcsu hop over here (https://github.com/Sensirion/embedded-sgp/issues/56).

I'm in a similar spot as you. I've asked @olirehacek to post his starter code so maybe that'd help you as well :)

**Comment by abrauchli** [comment]
Hey @sgowdarcsu, @worldburger  - it'd help if you could post your issues (e.g. compiler errors), what version you're using and if you clone it from git or used the release-zip and what arduino board you're running off, as they all behave a bit differently.
If you don't get output, it seems that your code is compiling. Did you add any output? Post a snippet of how you're using the driver.

We unfortunately don't have the manpower to provide coding support, but we're aware of the entry threshold for novices and we plan on improving it in the long run.

**Comment by MBjoern** [comment]
There are ready to use Arduino examples for the new [SVM40 sensor module](https://www.sensirion.com/my-sgp-ek/)
You'll find the corresponding arduino lirbaries in the Arduino library manager or [here](https://github.com/sensirion?q=arduino+svm40)

**Comment by MBjoern** [comment]
Issue is being closed due to inactivity
